source 'https://github.com/CocoaPods/Specs.git'

target 'JVFloatingDrawer' do
	pod "JVFloatingDrawer", :path => "../"
    
    target 'JVFloatingDrawerTests' do
        inherit! :search_paths
    end
end
